### ISSUE TITLE
Race-condition when starting istio-cni before calico or canal

### ISSUE THREAD

**Issue by jeckhart** [istio/cni#82]
Our dev environment is a kops (v1.11.0) deployed kubernetes cluster (v1.11.7) with canal (calico + flannel).

We are using istio-cni (0.1-dev). When starting a new node istio-cni reliably starts faster than calico-cni.

This results in istio-cni creating a config file (in this case `10-canal.conflist`) that is later overwritten by the calico-cni startup. The end result is that istio-cni is not deployed because it's config is overwritten.

I've updated the startup command for istio-cni to wait for the conf file to exist before starting. The relevant parts look like:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - while [[ -n "${CNI_CONF_NAME}" ]] && [[ ! -e "/host/etc/cni/net.d/${CNI_CONF_NAME}"
          ]]; do echo Waiting for cni to stabilize; sleep 1; done; /install-cni.sh
        command:
        - /bin/bash
...
```

I'm looking for feedback on how others are handling this. Is anybody else encountered a race with istio-cni? Are there other solutions? If not, should I submit this as a PR (adding an option to make if configurable)?
